import Head from 'next/head';
import Image from 'next/image';
import web1 from '../public/web1.png';
import myimage from '../public/myimage.png';
import myimage2 from '../public/myimage2.png';
import restaurant from '../public/restaurant.png';
import threesixfive from '../public/365.png';
import blog from '../public/blog.png';
// import resume from '../public/Affiahmma.pdf';
import { AiFillSetting } from 'react-icons/ai';
import { AiFillMail } from 'react-icons/ai';
import { BsCodeSlash, BsFileCheck } from 'react-icons/bs';
import { BsTelephone } from 'react-icons/bs';
import { BsLinkedin } from 'react-icons/bs';
import { BsGithub } from 'react-icons/bs';
import { BsTwitter } from 'react-icons/bs';
import { BsInstagram } from 'react-icons/bs';





export default function Home() {
  return (
    <div className='bg-dark'>
      <Head>
        <title>Precious Affiah Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='px-10 md:px-5 lg:px-40'>
        <section className='min-h-screen'>
          <div className="relative">
            <div clasName="fixed top-4 left-0 right-0">
              <nav className='lg:py-4 py-3 mb-2 flex justify-between lg:px-20 px-4 rounded-full'>
                <h1 className='lg:text-xl text-sm font-burtons text-teal-500'>developedbyprecious</h1>
                <ul className='flex items-center'>
                  <li>
                    <a className=' bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href={myimage2}>Resume</a>
                  </li>
                </ul>
              </nav>
            </div>
          </div>
          <div className='text-center pt-28'>
            <h2 className='lg:text-5xl text-3xl py-2 text-teal-600 font-medium md:text-6xl'>Hi, I am Precious Affiah</h2>
            <h3 className='lg:text-3xl md:text-3xl text-xl py-2 text-white'>A web developer.</h3>
            <div className=' mx-auto w-auto lg:w-5/12 md:w-4/12'>
              <Image src={myimage} alt={'myimage'} />
            </div>
          </div>
          <div className='lg:flex gap-10 items-center py-8'>
            <div className='text-center rounded-xl hidden lg:block'>
              <div className='mx-auto' style={{ width: '350px' }}>
                <Image src={myimage2} alt={'myimage'}/>
              </div>
            </div>
            <div className='text-center rounded-xl'>
              <h5 className='font-medium text-teal-500 text-4xl'>About Me</h5>
              <p className='py-2 text-white text-xl'>
                Hi guys!, my name is precious Affiah and I am a fullstack developer, I am from a family of four(4) and the last. I am a young ambitious girl whose limit is non existent!. English is my first language as well as Efik. I am teachable and have an eagerness to learn new things. I believe i can do all things through christ who strengthens me! This is my mantra! (philipians 4:13)
              </p>
            </div>
          </div>
          <section>
            <div className='lg:py-12 text-center py-3 text-white'>
              <ul className='lg:py-11 flex w-100 py-5 lg:text-5xl text-4xl font-bold text-center justify-center'>
                <li className='-mt-1.5'>
                  Skills
                </li>
                <li>
                  <BsCodeSlash />
                </li>
              </ul>
              <div className=' justify-center w-100'>
                <ul className='lg:text-4xl lg:py-2 md:justify-evenly md:text-xl text-base flex justify-between w-100 pt-0'>
                  <li>HTML</li>
                  <li>CSS</li>
                  <li>Javascript</li>
                  <li>ReactJs</li>
                  <li>NodeJs</li>
                </ul>
                <ul className='lg:text-4xl lg:py-2 md:justify-evenly md:text-xl text-base flex justify-between w-100 pb-5'>
                  <li>Bootstrap</li>
                  <li>Tailwind</li>
                  <li>ExpressJs</li>
                  <li>NextJs</li>
                </ul>
              </div>
            </div>
          </section>
          <section className='lg:py-8 pb-0 text-white'>
            <ul className='lg:py-11 flex w-100 py-5 lg:text-5xl text-4xl font-bold text-center justify-center'>
              <li className='-mt-1.5'>
                Services
              </li>
              <li>
                <AiFillSetting />
              </li>
            </ul>
            <div className='lg:flex lg:py-8 py-3 gap-10'>
              <div className='text-center lg:mb-0 mb-11 lg:p-6 p-3 rounded-2xl border-2'>
                <p>
                  About Me
                  Hello, my name is Foster (Tope Akintola). I am 21 years old and I am currently studying Web Design and Development. I am passionate about this field and it is my goal to become very proficient in this industry. I am currently studying Computer Science. I also have a keen interest in new technologies such as Blockchain, AI, VR/AR, Cloud, Cyber Security, and Cryptocurrency. I am hard working, reliable, and self-motivated. I have a MacBook so I can work remotely and deliver all required tasks online. I am currently looking for an entry-level freelance or volunteer position that will help me gain some practical experience and build my portfolio.
                </p>
              </div>
              <div className='text-center lg:p-6 p-3 rounded-2xl border-2'>
                <p>
                  About Me
                  Hello, my name is Foster (Tope Akintola). I am 21 years old and I am currently studying Web Design and Development. I am passionate about this field and it is my goal to become very proficient in this industry. I am currently studying Computer Science. I also have a keen interest in new technologies such as Blockchain, AI, VR/AR, Cloud, Cyber Security, and Cryptocurrency. I am hard working, reliable, and self-motivated. I have a MacBook so I can work remotely and deliver all required tasks online. I am currently looking for an entry-level freelance or volunteer position that will help me gain some practical experience and build my portfolio.
                </p>
              </div>
            </div>
          </section>
          <section className='py-8 text-white '>
            <ul className='lg:py-11 flex w-100 py-5 lg:text-5xl text-4xl font-bold text-center justify-center'>
              <li className='-mt-1.5'>
                Projects
              </li>
              <li>
                <BsFileCheck />
              </li>
            </ul>
            <div className='lg:flex gap-10 py-8'>
              <div className='lg:m-0 mb-12 text-center p-4 rounded-2xl border-2 md:w-2/3 w-auto lg:w-1/3 mx-auto'>
                <Image src={restaurant} alt={'restaurant'} className='rounded-lg'  width={'100%'} height={'100%'} layout='responsive' />

                <p className='pt-4'> 
                <h5 className='font-bold text-white text-2xl'>Pizza restaurant</h5>
                The Pizza restaurant is one out of many projects that was done in the Mississippi Coding Academies class, focusing on HTML, CSS and BOOTSTRAP5 and is fully responsive. 
                </p>
                <p className='m-auto bg-gradient-to-r from-cyan-500 to-teal-500 rounded-md p-2 mt-2 text-center w-5/12'>
                  <a href='https://github.com/preciousaffiah'>Github</a>
                </p>
              </div>
              <div className='lg:m-0 mb-12 text-center p-4 rounded-2xl border-2 md:w-2/3 w-auto lg:w-1/3 mx-auto'>
                <Image src={threesixfive} alt={'threesixfive'} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive' />
                <p className='pt-4'>
                <h5 className='font-bold text-white text-2xl'>Article web application</h5>
                365 is an E-ticketing platform where event organizers post their events and pay a fee to the platform so that the users can purchase an e-ticket for the event of their choice with the use of a bar code for each ticket bought and 365 also helps organizers advertise their events on the 365 social media platforms for no extra cost. This project was built with HTML, CSS, BOOTSTRAP, Javascript, NodeJs and MongoDB.
                </p>
                <p className='m-auto bg-gradient-to-r from-cyan-500 to-teal-500 rounded-md p-2 mt-2 text-center w-1/2'>
                <a href='https://365eventcompany.com/' target={'_blank'} rel='noreferrer'>
                View Website
                </a>
                </p>
              </div>
              <div className='lg:m-0 mb-12 text-center p-4 rounded-2xl border-2 md:w-2/3 w-auto lg:w-1/3 m-auto'>
                <Image src={blog} alt={'blog'} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive' />
                <p className='pt-4'>
                <h5 className='font-bold text-white text-2xl'>365 E-ticketing web application</h5>
                The article/blog web application was made to let users post their articles and view articles posted by other users. The article/blog web application was made with the google login API, Node.JS for backend, ReactJS for frontend and MongoDB for database.
                </p>
                <p className='m-auto bg-gradient-to-r from-cyan-500 to-teal-500 rounded-md p-2 mt-2 text-center w-5/12'>
                <a href='https://github.com/preciousaffiah' target={'_blank'} rel='noreferrer'>
                Github
                </a>
                </p>
              </div>
            </div>
          </section>
          <section>
            <div className='lg:py-12 text-center py-3 text-white'>
              <ul className='lg:py-11 flex w-100 py-5 lg:text-5xl text-3xl font-bold text-center justify-center'>
                <li className='flex -mt-1.5'>
                  Holla at ya girl...
                  <BsTelephone />
                </li>
              </ul>
              <div className=' justify-center w-100'>
                <ul className='lg:text-4xl lg:py-2 lg:flex md:flex md:text-3xl justify-between text-xl block w-100 pt-0'>
                  <a href='https://www.linkedin.com/in/precious-affiah-008753238/' target={'_blank'} rel='noreferrer'>
                  <li className='flex -mt-1.5 lg:justify-start justify-center'>
                    LinkedIn
                    <BsLinkedin/>
                    </li>
                  </a>
                  <a href='https://github.com/preciousaffiah' target={'_blank'} rel='noreferrer'>
                    <li className='flex lg:justify-start justify-center'>
                    Github
                    <BsGithub/>
                    </li>
                  </a>
                  <a href='https://twitter.com/The1homegirl' target={'_blank'} rel='noreferrer'>
                    <li className='flex lg:justify-start justify-center'>
                    Twitter
                    <BsTwitter/>
                    </li>
                  </a>
                  <a href='https://www.instagram.com/preciousaffiah/' target={'_blank'} rel='noreferrer'>
                    <li className='flex lg:justify-start justify-center'>
                    Instagram
                    <BsInstagram/>
                    </li>
                  </a>
                  <a href='mailto:preciousaffiah205@gmail.com' target={'_blank'} rel='noreferrer'>
                    <li className='flex lg:justify-start justify-center'>
                    Email
                    <AiFillMail className='flex mt-1.5'/>
                    </li>
                  </a>
                </ul>
              </div>
            </div>
          </section>
        </section>
      </main>
      <footer>
        <section>
          <div className='py-4 px-10 text-white lg:text-lg text-sm'>
            <p>© Created by Precious Affiah 2022</p>
          </div>
        </section>
      </footer>
    </div>
  )
}
